Add option for `pdm lock` flags and test

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2,20 +2,27 @@ name: 'PDM Multirepo branches'
 description: 'For git+https dependencies, check if the current branch name exitsts there and use it if it does'
 inputs:
   working-directory:
-    description: 'working directory'
+    description: 'Working directory'
     required: false
+    type: string
     default: './'
+  pdm-lock-flags:
+    description: 'Flags to use for PDM lock'
+    required: false
+    type: string
+    default: "--prod"
 outputs:
   overrides-generated:
     description: "True if overrides were generated and used"
     value: ${{ steps.gen-overrides.outputs.overrides_generated }}
+
 runs:
   using: "composite"
   steps:
     - name: Check PDM initialised
       shell: bash
       run: |
-        pdm show || echo "::error Calling workflow must initialise PDM first (use pdm-project/setup-pdm)"
+        pdm > /dev/null 2>&1 || echo "::error Calling workflow must initialise PDM first (use pdm-project/setup-pdm)"
 
     - name: Generate overrides to use current branch if PR
       id: gen-overrides
@@ -30,12 +37,10 @@ runs:
           echo "overrides_generated=1" >> "$GITHUB_OUTPUT"
           echo "** Using overrides for $GITHUB_JOB **" > override.msg
           cat overrides.txt >> override.msg
-        else
-          echo "overrides_generated=2" >> "$GITHUB_OUTPUT"
         fi
 
     - name: Message overrides
-      if: github.event_name == 'pull_request' && ${{ steps.gen-overrides.overrides_generated }}
+      if: ${{ steps.gen-overrides.overrides_generated && github.event_name == 'pull_request' }}
       uses: thollander/actions-comment-pull-request@v3
       with:
         file-path:  '${{ inputs.working-directory }}/override.msg'
@@ -46,13 +51,17 @@ runs:
       working-directory: ${{ inputs.working-directory }}
       if: github.event_name != 'pull_request'
       shell: bash
-      run: pdm lock -d
+      env:
+        PDM_LOCK_FLAGS: '${{inputs.pdm-lock-flags}}'
+      run: pdm lock $PDM_LOCK_FLAGS
 
     - name: Relock PDM (PR)
       working-directory: ${{ inputs.working-directory }}
       if: github.event_name == 'pull_request'
       shell: bash
-      run: pdm lock -d --override overrides.txt
+      env:
+        PDM_LOCK_FLAGS: '${{inputs.pdm-lock-flags}}'
+      run: pdm lock $PDM_LOCK_FLAGS --override overrides.txt
 
     - name: Install dependencies
       working-directory: ${{ inputs.working-directory }}
